### ISSUE TITLE
JJM data dump of 1.7 million habitations and mappings to villages.

### ISSUE THREAD

**Issue by ramSeraph** [justinelliotmeyers/INDIA_DATA_DUMP_2022#4]
I have it.. waiting on some legal clarifications.. Will make them available if you think it will help.

Currently a little busy with something else.

**Comment by justinelliotmeyers** [comment]
Would love to see the data! If a clear license exists, that would be super helpful. Really appreciate this!

**Comment by ramSeraph** [comment]
Terms and conditions listed are at https://jalshakti-ddws.gov.in/website-policies-0

My interpretation is that sending you data is ok but publishing it is not.. anyway.. dm me on twitter( same username )

**Comment by ramSeraph** [comment]
Also, we are in the middle of getting clarity on Indian opendata policies.. if it turns out positive.. that terms and conditions might be invalid and it might be ok to publish the data anyway

**Comment by justinelliotmeyers** [comment]
@ramSeraph we can discuss this after we have more time to eval the data.gov.in dumps and see if we can get a full download from them to qc against everything out so far. Appreciate your insight with this data, will be super helpful in the future!
Justin
